---
abstract: ~
author:
  - 'Kevin W. Henwood <Khen1950fx@yahoo.com>'
build_requires:
  ExtUtils::MakeMaker: '6.36'
  Test: 0
configure_requires:
  ExtUtils::MakeMaker: '6.36'
distribution_type: module
dynamic_config: 1
generated_by: 'Module::Install version 1.06'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: Task-Git-LongList1
no_index:
  directory:
    - inc
    - t
requires:
  Any::Moose: 0
  Archive::Extract: 0
  Attribute::Handlers: 0
  AutoLoader: 0
  B::Hooks::EndOfScope: 0
  B::Hooks::OP::Annotation: 0
  B::Hooks::OP::Check: 0
  B::Keywords: 0
  B::OPCheck: 0
  B::Utils: 0
  CGI: 0
  CPAN::Meta: 0
  CSS: 0
  Capture::Tiny: 0
  Carp: 0
  Carp::Clan: 0
  Catalyst: 0
  Class::Data::Inheritable: 0
  Class::Factory::Util: 0
  Class::Inspector: 0
  Class::Load: 0
  Class::Load::XS: 0
  Class::Method::Modifiers: 0
  Class::Singleton: 0
  Class::Tiny: 0
  Clone: 0
  Compress::Raw::Bzip2: 0
  Compress::Raw::Zlib: 0
  Compress::Zlib: 0
  Config::GitLike: 0
  Config::Tiny: 0
  Const::Fast: 0
  Crypt::SSLeay: 0
  DBM::Deep: 0
  Data::Dumper: 0
  Data::OptList: 0
  Data::Stream::Bulk: 0
  Data::Util: 0
  Date::Parse: 0
  DateTime: 0
  DateTime::Event::ICal: 0
  DateTime::Event::Recurrence: 0
  DateTime::Format::Builder: 0
  DateTime::Format::DateParse: 0
  DateTime::Format::Flexible: 0
  DateTime::Format::ICal: 0
  DateTime::Format::Natural: 0
  DateTime::Format::Strptime: 0
  DateTime::Locale: 0
  DateTime::Set: 0
  DateTime::TimeZone: 0
  DateTimeX::Easy: 0
  Devel::CallChecker: 0
  Devel::CallParser: 0
  Devel::CheckCompiler: 0
  Devel::Declare: 0
  Devel::Declare::MethodInstaller::Simple: 0
  Devel::GlobalDestruction: 0
  Devel::PPPort: 0
  Devel::Pragma: 0
  Devel::StackTrace: 0
  Devel::Symdump: 0
  Digest: 0
  Digest::MD5: 0
  Digest::SHA: 0
  Dist::CheckConflicts: 0
  DynaLoader::Functions: 0
  Email::Address: 0
  Encode: 0
  Encode::Locale: 0
  Env::Path: 0
  Error: 0
  Eval::Closure: 0
  Exception::Class: 0
  Exporter: 0
  Exporter::Declare: 0
  ExtUtils::CBuilder: 0
  ExtUtils::Config: 0
  ExtUtils::Depends: 0
  ExtUtils::Helpers: 0
  ExtUtils::Install: 0
  ExtUtils::MakeMaker: 0
  ExtUtils::ParseXS: 0
  FCGI: 0
  Fennec::Lite: 0
  File::Copy::Recursive: 0
  File::Find::Rule: 0
  File::Listing: 0
  File::Path: 0
  File::Remove: 0
  File::ShareDir: 0
  File::ShareDir::Install: 0
  File::ShareDir::ProjectDistDir: 0
  File::Slurp: 0
  File::Spec: 0
  File::Temp: 0
  File::Which: 0
  File::pushd: 0
  Filter::Util::Call: 0
  Gerrit::REST: 0
  Getopt::Long: 0
  Getopt::Mini: 0
  Git::Class: 0
  Git::FastExport: 0
  Git::Gitalist: 0
  Git::Hook::PostReceive: 0
  Git::Hooks: 0
  Git::Hooks::PerlCritic: 0
  Git::Open: 0
  Git::PurePerl: 0
  Git::Release: 0
  Git::Repository: 0
  Git::Repository::Plugin::AUTOLOAD: 0
  Git::SVNReplay: 0
  Git::Sub: 0
  Git::Validate: 0
  Git::Wrapper: 0
  Git::XS: 0
  HTML::Element: 0
  HTML::Entities: 0
  HTML::Form: 0
  HTML::Tagset: 0
  HTML::Tree: 0
  HTML::TreeBuilder: 0
  HTML::WikiConverter: 0
  HTML::WikiConverter::Markdown: 0
  HTTP::Cookies: 0
  HTTP::Daemon: 0
  HTTP::Date: 0
  HTTP::Negotiate: 0
  HTTP::Server::Simple: 0
  HTTP::Status: 0
  Hash::Util::FieldHash::Compat: 0
  Hook::LexWrap: 0
  IO::All: 0
  IO::Capture: 0
  IO::Digest: 0
  IO::HTML: 0
  IO::Handle: 0
  IO::Pty: 0
  IO::Socket::SSL: 0
  IO::String: 0
  IPC::Cmd: 0
  IPC::Run: 0
  IPC::Run3: 0
  IPC::System::Simple: 0
  Import::Into: 0
  JSON: 0
  JSON::PP: 0
  LWP::MediaTypes: 0
  LWP::Protocol::https: 0
  LWP::UserAgent: 0
  Lexical::SealRequireHints: 0
  Lingua::EN::Inflect: 0
  List::MoreUtils: 0
  Locale::Maketext: 0
  Log::Dump: 0
  MIME::Base64: 0
  MRO::Compat: 0
  Meta::Builder: 0
  Method::Signatures: 0
  Method::Signatures::Simple: 0
  Mixin::Linewise::Readers: 0
  Mo: 0
  Mock::Quick: 0
  Module::Build: 0
  Module::Build::Tiny: 0
  Module::Build::XSUtil: 0
  Module::Find: 0
  Module::Implementation: 0
  Module::Load: 0
  Module::Pluggable: 0
  Module::Runtime: 0
  Module::Util: 0
  Moo: 0
  MooX::Types::MooseLike: 0
  Moose::Util::TypeConstraints: 0
  MooseX::AttributeHelpers: 0
  MooseX::ConfigFromFile: 0
  MooseX::Getopt: 0
  MooseX::MethodAttributes: 0
  MooseX::Role::Parameterized: 0
  MooseX::Role::WithOverloading: 0
  MooseX::SimpleConfig: 0
  MooseX::Storage: 0
  MooseX::StrictConstructor: 0
  MooseX::Types: 0
  MooseX::Types::Common: 0
  MooseX::Types::DateTime: 0
  MooseX::Types::Moose: 0
  MooseX::Types::Path::Class: 0
  MooseX::Types::Path::Tiny: 0
  MooseX::Types::Stringlike: 0
  Mouse: 0
  Mozilla::CA: 0
  Net::FTP: 0
  Net::HTTP: 0
  Net::Netrc: 0
  Net::Redmine: 0
  Net::SSLeay: 0
  Number::Compare: 0
  PPI: 0
  PPIx::Regexp: 0
  PPIx::Utilities::Statement: 0
  Package::DeprecationManager: 0
  Package::Stash: 0
  Package::Stash::XS: 0
  Params::Util: 0
  Params::Validate: 0
  Parse::CPAN::Meta: 0
  Parse::RecDescent: 0
  Path::Class: 0
  Path::Extended: 0
  Path::FindDev: 0
  Path::IsDev: 0
  Path::Tiny: 0
  Perl::Critic: 0
  Perl::MinimumVersion: 0
  Perl::OSType: 0
  Perl::Tidy: 0
  PerlIO::via::dynamic: 0
  Pod::Coverage: 0
  Pod::Coverage::CountParents: 0
  Pod::Coverage::TrustPod: 0
  Pod::Escapes: 0
  Pod::Eventual::Simple: 0
  Pod::Man: 0
  Pod::Parser: 0
  Pod::Simple: 0
  Pod::Spell: 0
  Pod::Usage: 0
  Pod::Wordlist: 0
  Probe::Perl: 0
  Quantum::Superpositions: 0
  REST::Client: 0
  Readonly: 0
  Readonly::XS: 0
  Regexp::Common: 0
  Regexp::Common::Email::Address: 0
  Role::Tiny: 0
  Scalar::Util: 0
  Scope::Guard: 0
  Set::Infinite: 0
  Sort::Versions: 0
  Specio::Declare: 0
  Storable: 0
  String::Format: 0
  String::RewritePrefix: 0
  String::ShellQuote: 0
  Sub::Exporter: 0
  Sub::Exporter::Progressive: 0
  Sub::Identify: 0
  Sub::Install: 0
  Sub::Name: 0
  Sub::StrictDecl: 0
  Sub::Uplevel: 0
  System::Command: 0
  TAP::Harness::Env: 0
  Task::Weaken: 0
  Term::ANSIColor: 0
  Term::ANSIScreen: 0
  Term::Encoding: 0
  Term::GentooFunctions: 0
  Term::ReadLine: 0
  Term::Size: 0
  Test: 0
  Test::Able: 0
  Test::CPAN::Changes: 0
  Test::CPAN::Meta: 0
  Test::CPAN::Meta::JSON: 0
  Test::Carp: 0
  Test::Classy: 0
  Test::Compile: 0
  Test::Cukes: 0
  Test::Deep: 0
  Test::DistManifest: 0
  Test::EOL: 0
  Test::Exception: 0
  Test::Exception::LessClever: 0
  Test::Fatal: 0
  Test::Git: 0
  Test::Harness: 0
  Test::LeakTrace: 0
  Test::Memory::Cycle: 0
  Test::MinimumVersion: 0
  Test::Mock::Cmd: 0
  Test::MockTime: 0
  Test::Mojibake: 0
  Test::Moose::More: 0
  Test::More: 0
  Test::Most: 0
  Test::NoTabs: 0
  Test::NoWarnings: 0
  Test::Object: 0
  Test::Output: 0
  Test::Pod: 0
  Test::Pod::Coverage: 0
  Test::Pod::LinkCheck: 0
  Test::Portability::Files: 0
  Test::Requires: 0
  Test::Script: 0
  Test::Spelling: 0
  Test::SubCalls: 0
  Test::Synopsis: 0
  Test::Taint: 0
  Test::TempDir: 0
  Test::Tester: 0
  Test::Vars: 0
  Test::Version: 0
  Test::Warn: 0
  Test::Warnings: 0
  Test::use::ok: 0
  Test::utf8: 0
  Text::Balanced: 0
  Text::CSV: 0
  Text::CSV::Slurp: 0
  Text::Glob: 0
  Text::Greeking: 0
  Text::ParseWords: 0
  Text::Wrap: 0
  Time::HiRes: 0
  Time::Local: 0
  Time::Piece: 0
  Tree::DAG_Node: 0
  Try::Tiny: 0
  URI: 0
  WWW::Mechanize: 0
  WWW::RobotRules: 0
  XS::Object::Magic: 0
  XSLoader: 0
  aliased: 0
  autodie: 0
  bareword::filehandles: 0
  base: 0
  boolean: 0
  constant: 0
  experimental: 0
  if: 0
  indirect: 0
  invoker: 0
  lib: 0
  methods: 0
  multidimensional: 0
  namespace::autoclean: 0
  namespace::clean: 0
  namespace::sweep: 0
  ok: 0
  pQuery: 0
  parent: 0
  perl: '5.005'
  strictures: 0
  true::VERSION: 0
  utf8::all: 0
  version: 0
resources:
  license: http://dev.perl.org/licenses/
version: '0.01'
