#!/usr/bin/perl

use strict;
use warnings;
use CPAN;

use Test::More tests => 131;

my (@mods) = qw(
    IO::Pty
    IPC::Run
    System::Command
    Git::Repository
    MooX::Types::MooseLike
    Import::Into
    Sub::Exporter::Progressive
    Devel::GlobalDestruction
    strictures
    Class::Method::Modifiers
    Moo
    Config::GitLike
    IPC::Cmd
    Dist::CheckConflicts
    Package::Stash
    Class::Load
    Text::Abbrev
    Attribute::Handlers
    Test::Requires
    Module::Implementation
    Params::Validate
    JSON::PP
    ExtUtils::Config
    ExtUtils::InstallPaths
    ExtUtils::ParseXS
    Pod::Man
    Module::Load
    ExtUtils::Helpers
    ExtUtils::Installed
    Module::Build::Tiny
    parent
    Test::Warnings
    Getopt::Long::Descriptive
    String::RewritePrefix
    IO::TieCombine
    Capture::Tiny
    App::Cmd::Setup
    Email::Address
    Config::Tiny
    PPIx::Regexp
    Module::Pluggable
    String::Format
    Perl::Tidy
    Text::ParseWords
    File::ShareDir::Install
    Path::FindDev
    Probe::Perl
    Test::Script
    File::Which
    File::HomeDir
    Module::Runtime
    Try::Tiny
    Test::Fatal
    Role::Tiny
    Path::IsDev
    Digest::SHA
    Digest
    Path::Tiny
    File::ShareDir::ProjectDistDir
    Class::Tiny
    version
    Lingua::EN::Inflect
    Text::Wrap
    Pod::Escapes
    Pod::Spell
    Test
    Devel::StackTrace
    Class::Data::Inheritable
    Exception::Class
    CPAN::Meta
    Readonly
    Data::Dumper
    PPIx::Utilities::Statement
    File::Path
    B::Keywords
    Pod::Usage
    List::MoreUtils
    Task::Weaken
    Class::Inspector
    Hook::LexWrap
    Test::SubCalls
    Clone
    Digest::MD5
    Storable
    Test::Object
    IO::String
    File::Remove
    PPI
    Perl::Critic
    Test::Perl::Critic
    Time::HiRes
    IPC::Run3
    Term::ReadLine
    Term::ANSIColor
    Getopt::Long
    CLI::Helpers
    Compress::Zlib
    Devel::Symdump
    Pod::Parser
    File::Temp
    constant
    Sub::Uplevel
    Test::Harness
    Test::Exception
    Module::Build
    XSLoader
    PerlIO::utf8_strict
    Encode
    Exporter
    Sub::Install
    Data::OptList
    lib
    ExtUtils::CBuilder
    Params::Util
    File::Spec
    Sub::Exporter
    IO::File
    Mixin::Linewise::Readers
    Carp
    Test::NoWarnings
    List::Util
    Test::Deep
    Test::More
    Pod::Eventual::Simple
    base
    Pod::Coverage::TrustPod
    ExtUtils::MakeMaker
    Mo
    YAML
    Git::Code::Review
);

foreach my $mod (@mods) {
    require_ok($mod);
}

